require('dotenv').config();
const express = require('express');
const session = require('express-session');
const crypto = require('crypto');
const { google } = require('googleapis');
const path = require('path');

const app = express();
const PORT = Number(process.env.PORT || 3000);
const isProd = process.env.NODE_ENV === 'production';
const SCOPES = ['https://www.googleapis.com/auth/gmail.readonly','https://www.googleapis.com/auth/gmail.send','https://www.googleapis.com/auth/gmail.modify'];
const MAX_RESULTS = 50;
const syncClients = new Map();
const mailboxState = new Map();

app.set('trust proxy', 1);
app.disable('x-powered-by');
app.use(express.json({ limit: '256kb' }));
app.use(session({ name:'nebula.sid', secret:process.env.SESSION_SECRET || (isProd ? crypto.randomBytes(48).toString('hex') : 'dev-only-change-me'), resave:false, saveUninitialized:false, cookie:{httpOnly:true,sameSite:'lax',secure:isProd,maxAge:86400000} }));

function oauth(){return new google.auth.OAuth2(process.env.GOOGLE_CLIENT_ID,process.env.GOOGLE_CLIENT_SECRET,process.env.GOOGLE_REDIRECT_URI || `http://localhost:${PORT}/auth/callback`)}
function client(req){const c=oauth();if(req.session.tokens)c.setCredentials(req.session.tokens);return c}
function requireAuth(req,res,next){if(!req.session.tokens)return res.status(401).json({error:'AUTH_REQUIRED'});next()}
function header(headers,name){return (headers||[]).find(h=>String(h.name).toLowerCase()===name.toLowerCase())?.value||''}
function decode(data){if(!data)return '';return Buffer.from(data.replace(/-/g,'+').replace(/_/g,'/'),'base64').toString('utf8')}
function bodyFromPayload(payload){if(!payload)return '';if(payload.mimeType==='text/plain'&&payload.body?.data)return decode(payload.body.data);for(const part of payload.parts||[]){const body=bodyFromPayload(part);if(body)return body}return ''}
function normalize(message){return {id:message.id,threadId:message.threadId,sender:header(message.payload?.headers,'From'),to:header(message.payload?.headers,'To'),cc:header(message.payload?.headers,'Cc'),subject:header(message.payload?.headers,'Subject')||'(no subject)',date:header(message.payload?.headers,'Date'),snippet:message.snippet||'',body:bodyFromPayload(message.payload),unread:(message.labelIds||[]).includes('UNREAD'),labels:message.labelIds||[],historyId:message.historyId||null}}
function gmail(req){return google.gmail({version:'v1',auth:client(req)})}
function appendQuery(req){const parts=[];if(req.query.q)parts.push(String(req.query.q));if(req.query.from)parts.push(`from:${String(req.query.from).trim()}`);if(req.query.keyword)parts.push(String(req.query.keyword).trim());if(req.query.unread==='true')parts.push('is:unread');if(req.query.after)parts.push(`after:${String(req.query.after)}`);if(req.query.before)parts.push(`before:${String(req.query.before)}`);return parts.filter(Boolean).join(' ').trim()}
function listOptions(req){const label=String(req.query.label||'INBOX').toUpperCase();const options={userId:'me',q:appendQuery(req),maxResults:Math.min(Math.max(Number(req.query.maxResults||MAX_RESULTS),1),MAX_RESULTS)};if(req.query.pageToken)options.pageToken=String(req.query.pageToken);if(['INBOX','SENT','DRAFT','STARRED','SPAM','TRASH'].includes(label))options.labelIds=[label];if(label==='ARCHIVE')options.q=`${options.q} -label:inbox -label:trash -label:spam`.trim();return options}
async function fetchMessages(req){const service=gmail(req);const list=await service.users.messages.list(listOptions(req));const ids=list.data.messages||[];const messages=await Promise.all(ids.map(x=>service.users.messages.get({userId:'me',id:x.id,format:'full'})));return {messages:messages.map(x=>normalize(x.data)),nextPageToken:list.data.nextPageToken||null,resultSizeEstimate:list.data.resultSizeEstimate||0}}
async function getProfile(req){return gmail(req).users.getProfile({userId:'me'})}
function publish(email,event){const clients=syncClients.get(email)||new Set();const payload=`event: ${event.type}\ndata: ${JSON.stringify(event)}\n\n`;for(const res of clients)res.write(payload)}
function rememberMailbox(email,req,historyId){mailboxState.set(email,{tokens:req.session.tokens,historyId:historyId||mailboxState.get(email)?.historyId||null,watchExpiration:mailboxState.get(email)?.watchExpiration||null})}
async function renewWatch(req,email){if(!process.env.PUBSUB_TOPIC)return {configured:false};const result=await gmail(req).users.watch({userId:'me',requestBody:{topicName:process.env.PUBSUB_TOPIC,labelIds:['INBOX'],labelFilterBehavior:'INCLUDE'}});const state=mailboxState.get(email)||{tokens:req.session.tokens};state.tokens=req.session.tokens;state.historyId=result.data.historyId||state.historyId;state.watchExpiration=result.data.expiration||null;mailboxState.set(email,state);return {configured:true,historyId:state.historyId,expiration:state.watchExpiration}}

app.get('/auth/url',(req,res)=>{const state=crypto.randomBytes(32).toString('hex');req.session.oauthState=state;const url=oauth().generateAuthUrl({access_type:'offline',prompt:'consent',include_granted_scopes:true,scope:SCOPES,state});res.json({url})});
app.get('/auth/callback',async(req,res)=>{try{if(!req.query.code||!req.query.state||req.query.state!==req.session.oauthState)return res.status(400).send('OAuth state validation failed. Please restart sign-in.');delete req.session.oauthState;const c=oauth();const {tokens}=await c.getToken(req.query.code);await new Promise((resolve,reject)=>req.session.regenerate(err=>err?reject(err):resolve()));req.session.tokens=tokens;res.redirect('/')}catch(e){res.status(400).send('OAuth failed: '+(e.message||'unknown error'))}});
app.post('/auth/logout',(req,res)=>req.session.destroy(()=>res.json({ok:true})));
app.get('/api/me',requireAuth,async(req,res)=>{try{const profile=await getProfile(req);const email=profile.data.emailAddress;rememberMailbox(email,req,profile.data.historyId);let push={configured:false};if(process.env.PUBSUB_TOPIC){try{push=await renewWatch(req,email)}catch(e){push={configured:false,error:e.message}}}res.json({email,historyId:profile.data.historyId||null,push})}catch(e){res.status(500).json({error:e.message})}});
app.get('/api/messages',requireAuth,async(req,res)=>{try{res.json(await fetchMessages(req))}catch(e){res.status(e.code===401?401:500).json({error:e.message})}});
app.get('/api/messages/:id',requireAuth,async(req,res)=>{try{res.json(normalize((await gmail(req).users.messages.get({userId:'me',id:req.params.id,format:'full'})).data))}catch(e){res.status(500).json({error:e.message})}});
app.get('/api/threads/:id',requireAuth,async(req,res)=>{try{const thread=await gmail(req).users.threads.get({userId:'me',id:req.params.id,format:'full'});res.json({id:thread.data.id,historyId:thread.data.historyId||null,messages:(thread.data.messages||[]).map(normalize)})}catch(e){res.status(500).json({error:e.message})}});
app.post('/api/messages/:id/read',requireAuth,async(req,res)=>{try{await gmail(req).users.messages.modify({userId:'me',id:req.params.id,requestBody:{removeLabelIds:['UNREAD']}});res.json({ok:true})}catch(e){res.status(500).json({error:e.message})}});
app.post('/api/send',requireAuth,async(req,res)=>{try{const {to,cc,bcc,subject,body,inReplyTo,references}=req.body||{};if(!to||!subject||!body)return res.status(400).json({error:'To, subject and body are required'});const headers=[`To: ${to}`];if(cc)headers.push(`Cc: ${cc}`);if(bcc)headers.push(`Bcc: ${bcc}`);headers.push(`Subject: ${subject}`);if(inReplyTo)headers.push(`In-Reply-To: ${inReplyTo}`);if(references)headers.push(`References: ${references}`);headers.push('MIME-Version: 1.0','Content-Type: text/plain; charset=utf-8');const raw=[...headers,'',body].join('\r\n');const result=await gmail(req).users.messages.send({userId:'me',requestBody:{raw:Buffer.from(raw).toString('base64url'),threadId:req.body.threadId||undefined}});res.json({ok:true,id:result.data.id,threadId:result.data.threadId||null})}catch(e){res.status(500).json({error:e.message})}});
app.get('/api/sync/status',requireAuth,async(req,res)=>{try{const email=(await getProfile(req)).data.emailAddress;const state=mailboxState.get(email)||{};res.json({mode:process.env.PUBSUB_TOPIC?'push+fallback':'polling',historyId:state.historyId||null,watchExpiration:state.watchExpiration||null,pollIntervalSeconds:Number(process.env.POLL_INTERVAL_SECONDS||30)})}catch(e){res.status(500).json({error:e.message})}});
app.post('/api/sync/watch',requireAuth,async(req,res)=>{try{if(!process.env.PUBSUB_TOPIC)return res.status(503).json({error:'PUBSUB_TOPIC is not configured'});const email=(await getProfile(req)).data.emailAddress;res.json(await renewWatch(req,email))}catch(e){res.status(500).json({error:e.message})}});
app.get('/api/events',requireAuth,async(req,res)=>{try{const email=(await getProfile(req)).data.emailAddress;res.set({'Content-Type':'text/event-stream','Cache-Control':'no-cache',Connection:'keep-alive','X-Accel-Buffering':'no'});res.flushHeaders?.();if(!syncClients.has(email))syncClients.set(email,new Set());syncClients.get(email).add(res);res.write(`event: ready\ndata: ${JSON.stringify({mode:process.env.PUBSUB_TOPIC?'push':'polling'})}\n\n`);const heartbeat=setInterval(()=>res.write(': heartbeat\n\n'),25000);req.on('close',()=>{clearInterval(heartbeat);syncClients.get(email)?.delete(res)})}catch{res.end()}});
app.post('/api/gmail/webhook',async(req,res)=>{try{if(process.env.PUBSUB_VERIFICATION_TOKEN&&req.query.token!==process.env.PUBSUB_VERIFICATION_TOKEN)return res.sendStatus(401);const encoded=req.body?.message?.data;if(!encoded)return res.sendStatus(204);const notification=JSON.parse(Buffer.from(encoded,'base64url').toString('utf8'));const email=notification.emailAddress;const state=mailboxState.get(email);if(!state?.tokens)return res.sendStatus(204);const c=oauth();c.setCredentials(state.tokens);const service=google.gmail({version:'v1',auth:c});const startHistoryId=state.historyId||notification.historyId;const changedIds=new Set();if(startHistoryId&&notification.historyId&&startHistoryId!==notification.historyId){let pageToken;do{const history=await service.users.history.list({userId:'me',startHistoryId,pageToken,maxResults:500});for(const item of history.data.history||[]){for(const group of ['messagesAdded','labelsAdded','labelsRemoved','messagesDeleted'])for(const entry of item[group]||[])if(entry.message?.id)changedIds.add(entry.message.id)}pageToken=history.data.nextPageToken;if(history.data.historyId)state.historyId=history.data.historyId}while(pageToken)}state.historyId=notification.historyId||state.historyId;mailboxState.set(email,state);publish(email,{type:'mailbox.changed',historyId:state.historyId,messageIds:[...changedIds]});res.sendStatus(204)}catch{res.sendStatus(500)}});

const tools=[
{name:'compose_email',description:'Prepare an email draft. Never send it.',input_schema:{type:'object',properties:{to:{type:'string'},cc:{type:'string'},subject:{type:'string'},body:{type:'string'}},required:['to','subject','body']}},
{name:'search_mail',description:'Search the authenticated Gmail mailbox using Gmail search syntax.',input_schema:{type:'object',properties:{query:{type:'string'},label:{type:'string',enum:['INBOX','SENT','DRAFT','STARRED','ARCHIVE']},maxResults:{type:'integer',minimum:1,maximum:10}},required:['query']}},
{name:'navigate_mail',description:'Navigate the mail UI to a folder.',input_schema:{type:'object',properties:{folder:{type:'string',enum:['INBOX','SENT','DRAFT','ARCHIVE','STARRED']}},required:['folder']}},
{name:'prepare_reply',description:'Prepare a reply draft using the currently open message context.',input_schema:{type:'object',properties:{body:{type:'string'}},required:['body']}}
];
async function callClaude(message,context){const response=await fetch('https://api.anthropic.com/v1/messages',{method:'POST',headers:{'content-type':'application/json','x-api-key':process.env.ANTHROPIC_API_KEY,'anthropic-version':'2023-06-01'},body:JSON.stringify({model:process.env.ANTHROPIC_MODEL||'claude-sonnet-4-6',max_tokens:1200,system:'You are Nebula Mail Copilot. Control the UI using tools. Never send an email. Compose actions must only create drafts for user review. For navigation/search, use tools rather than merely describing what to do. When asked to reply, use the provided current message context. Be concise and operational.',tools,messages:[{role:'user',content:`User request: ${message}\n\nCurrent UI context:\n${JSON.stringify(context||{})}`}]})});const data=await response.json();if(!response.ok)throw new Error(data.error?.message||`Anthropic request failed (${response.status})`);return data}
async function searchForAssistant(req,input){const fakeReq={...req,query:{q:input.query||'',label:input.label||'INBOX',maxResults:Math.min(input.maxResults||5,10)}};const result=await fetchMessages(fakeReq);return {query:input.query,messages:result.messages.map(m=>({id:m.id,threadId:m.threadId,sender:m.sender,subject:m.subject,date:m.date,snippet:m.snippet,unread:m.unread}))}}
async function assistant(req,message,context){if(!message)return {text:'Tell me what you want to do.',actions:[]};if(process.env.ANTHROPIC_API_KEY){try{const response=await callClaude(message,context);const actions=[];let text=(response.content||[]).filter(x=>x.type==='text').map(x=>x.text).join('\n').trim();for(const block of response.content||[]){if(block.type!=='tool_use')continue;if(block.name==='compose_email')actions.push({type:'compose',data:block.input});if(block.name==='prepare_reply'){const m=context?.currentMessage;if(!m)actions.push({type:'message',text:'Open an email first so I can prepare a contextual reply.'});else actions.push({type:'compose',data:{to:m.sender,subject:/^re:/i.test(m.subject)?m.subject:`Re: ${m.subject}`,body:`${block.input.body}\n\nOn ${m.date}, ${m.sender} wrote:\n> ${(m.body||m.snippet||'').slice(0,2000).replace(/\n/g,'\n> ')}`,threadId:m.threadId}})}if(block.name==='navigate_mail')actions.push({type:'navigate',folder:block.input.folder});if(block.name==='search_mail')actions.push({type:'search_results',...(await searchForAssistant(req,block.input))})}return {text:text||'Done.',actions,ai:true,model:process.env.ANTHROPIC_MODEL||'claude-sonnet-4-6'}}catch{}}
return fallbackAssistant(message,context)}
function fallbackAssistant(message,context){const low=message.toLowerCase();if(/reply/.test(low)&&context?.currentMessage){const m=context.currentMessage;return {text:'I prepared a reply draft from the current message. Review it before sending.',actions:[{type:'compose',data:{to:m.sender,subject:/^re:/i.test(m.subject)?m.subject:`Re: ${m.subject}`,body:'Thanks for your message.\n\n',threadId:m.threadId}}],ai:false}}const email=message.match(/[A-Z0-9._%+-]+@[A-Z0-9.-]+\.[A-Z]{2,}/i)?.[0]||'';if(/send|compose|email/.test(low)&&email)return {text:'I prepared the email details I could identify. Review them before sending.',actions:[{type:'compose',data:{to:email,subject:'',body:''}}],ai:false};if(/sent/.test(low))return {text:'Navigating to Sent.',actions:[{type:'navigate',folder:'SENT'}],ai:false};if(/archive/.test(low))return {text:'Navigating to Archive.',actions:[{type:'navigate',folder:'ARCHIVE'}],ai:false};if(/draft/.test(low))return {text:'Navigating to Drafts.',actions:[{type:'navigate',folder:'DRAFT'}],ai:false};if(/star/.test(low))return {text:'Showing starred mail.',actions:[{type:'navigate',folder:'STARRED'}],ai:false};if(/inbox/.test(low))return {text:'Navigating to Inbox.',actions:[{type:'navigate',folder:'INBOX'}],ai:false};if(/unread/.test(low))return {text:'Showing unread mail.',actions:[{type:'filter',unread:true}],ai:false};const last=low.match(/last\s+(\d+)\s+days?/);if(last)return {text:`Showing mail from the last ${last[1]} days.`,actions:[{type:'filter',days:Number(last[1])}],ai:false};return {text:'I can search mail, navigate folders, prepare replies, or open Compose. Add ANTHROPIC_API_KEY to enable Claude tool calling.',actions:[],ai:false}}
app.post('/api/assistant',requireAuth,async(req,res)=>{try{res.json(await assistant(req,String(req.body?.message||''),req.body?.context||null))}catch(e){res.status(500).json({error:e.message})}});

app.use(express.static(path.join(__dirname,'public')));
app.get('*',(req,res)=>res.sendFile(path.join(__dirname,'public','index.html')));
if(require.main===module)app.listen(PORT,()=>console.log(`AI Mail WebApp running on http://localhost:${PORT}`));
module.exports={app,normalize,bodyFromPayload,appendQuery,listOptions};
